## Variables and types

In Python a **variable** holds information. The information that it is holding (numbers, text, etc.) can be of different **types**. Declaring a variable in Python is simple. For example to set the variable `a` to `3`, you would do:

In [1]:
a = 3

To set a variable, you use the `=` operator. Python automatically determines the type of variable based on the format of the input. The above will automatically be considered an `int` (short for integer). The four types that you will use most are integers, strings, floats, and booleans. Let's briefly talk about each one along with some examples.

_Style note_: There are a couple of ways to define variable names. In general, in Python you never should start a variable name with a capital letter. This kind of naming is generally reserved for objects (which we will not explore in depth in this course). There are two commonly used styles for variables: underscore separated and CamelCase (or CapWords in PEP 8 parlance). For example, if you are using underscores, you would define: `my_variable` where for camelCase you would define `myVariable`. The PEP 8 style guide isn't conclusive on which should use for variables (it is specific for functions), but I get the sense that underscores may be preferred. Where possible a single word is best.

#### Integers
An integer is a whole number. To define an integer, simply entering a whole number when you assign the variable is sufficient.

In [2]:
type(a)

int

You can be sure of the type of your variable by using the `type()` function. As you can see here, Python correctly assumed that `a` was of type `int`. Now we'll define another variable that holds another `int`.

In [3]:
b = 2
type(b)

int

Now we can do an operation with this `int`. In contrast to Python 2, Python 3 will evaluate the result as a `float`, which will disucss next.

In [4]:
c = a/b
print(c)
type(c)

1.5


float

If you want to convert the result to an `int`, you can do that with the function `int()`:

In [5]:
c = int(c)
print(c)
type(c)

1


int

Notice that when you convert a `float` to an `int` it will always convert into the whole number before the floating point, e.g.:

In [6]:
a = 99/100
print(a)

0.99


In [7]:
a = int(a)
print(a)

0


#### Float
A `float` is a floating point number (anything number for which you use a floating decimal point). In order for Python to recognize a float, the number must contain a decimal point. Here are three ways that you could define a `float`:

In [8]:
a = 99.0
print(a)
type(a)

99.0


float

In [9]:
a = 99.
print(a)
type(a)

99.0


float

In [10]:
a = float(99)
print(a)
type(a)

99.0


float

As you can see with each of those examples, the way that Python prints `99.0` is consistent, even though we instantiated the variable in different ways. This is because it is also stored in memory in a consistent way.

You can also conduct an operation with both `int` and `float`. The result will always evaluate to a `float`.

In [11]:
a = 2
b = 4.
c = b/a
print(c)
type(c)

2.0


float

#### Strings
Strings are the way to store character information in Python. A string can be of any length and can include any valid character. 

You can assign a variable to string by enclosing the characters in single or double quotes. 

_Style note_: Python does not distinguish between single and double quotes, however, it is good to be consistent in your code.

In [12]:
sentence = "I love Python!"
type(sentence)

str

You can also convert and `int` or a `float` into a string with the `str()` function.

In [13]:
print(a)
type(a)

2


int

In [14]:
a = str(a)
print(a)
type(a)

2


str

Notice that now that we have converted `a` into a string, it is no longer computatble with an `int`.

In [15]:
c = a/b

TypeError: unsupported operand type(s) for /: 'str' and 'float'

However, there are operations that you can still conduct on strings. One is the `+` operator. However, as you may have noticed with last week's homework, it might not work exactly as you envision. Here is an example:

In [16]:
b = str(b)
c = a + b
print(c)
type(c)

24.0


str

It's clear that `24.0` is not the sum of `2` and `4.0`. You might have noticed that the `+` operator simply concatenates strings. Let's try it with something that will make it a bit more clear:

In [17]:
first = "Hello my name is "
second = "Paul."
phrase = first + second
print(phrase)

Hello my name is Paul.


You will learn more about strings in the next exercise.

#### Booleans
Booleans (`bool`) are a simple `type` in Python. A boolean can either be `True` or `False`. They can be really useful later on when we learn about conditionals and functions.

To set a variable to a boolean, you simply use the word `True` or `False` without any quotes around it.

In [18]:
fun = True
print(fun)
type(fun)

True


bool

In [19]:
fun = False
print(fun)
type(fun)

False


bool

We will learn more about booleans later on.